on:
  push:
    branches:
    - main
  pull_request:
name: downstream
jobs:
  dependencies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [11]
        repo:
        - java-bigquery
        - java-bigqueryconnection
        - java-spanner
        - java-storage
        - java-pubsub
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{matrix.java}}
    - run: java -version
    - run: sudo apt-get update -y
    - run: sudo apt-get install libxml2-utils
    - run: .kokoro/client-library-check.sh ${{matrix.repo}} dependencies

  flatten-plugin-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - run: java -version
    - run: sudo apt-get update -y
    - run: sudo apt-get install libxml2-utils
    - run: .kokoro/client-library-check.sh java-storage flatten-plugin
      env:
        REPO_TAG: v2.9.3
        EXPECTED_DEPENDENCIES_LIST: java-storage-expected-flattened-dependencies.txt
